[workspace]
repository = "github.com/akhilles/stdlib"
resolver = "2"
pcb-version = "0.2"
members = []

[assets]
"gitlab.com/kicad/libraries/kicad-footprints" = "9.0.3"
"gitlab.com/kicad/libraries/kicad-symbols" = "9.0.3"
